### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by izaclorimer** [dguzzo/NYT#6]
Just so you know, you have made your API keys public to the internet. You may want to remove them and refresh them for your own good.

**Comment by dguzzo** [comment]
oops, wasn't paying attention. thanks! 

(it's just a random toy app, not too worried about it, but yeah: shouldn't be public)

**Comment by izaclorimer** [comment]
Yeah, just thought I would let you know. (A small bit of context: http://files.gordhoard.org/files/images/0b6401.PNG)

**Comment by dguzzo** [comment]
:) yeah, should be an env var on the node process; i was lazy when building this 2-3 years ago. thanks for looking out.

**Comment by dguzzo** [comment]
133b447ae92947042c675cae421bcbd273ddbbc6

(rebased to remove the addition of the api key in the nyt.js source file)
